### ISSUE TITLE
finite volume method

### ISSUE THREAD

**Issue by marwahaha** [rachelslaybaugh/NE155#18]
For the finite volume method, should ![codecogseqn](https://cloud.githubusercontent.com/assets/2541209/13769103/0b811264-ea3a-11e5-8bcb-135782744384.gif)
 be 
![codecogseqn 2](https://cloud.githubusercontent.com/assets/2541209/13769119/42b6ea7e-ea3a-11e5-87ba-71fc8f288e91.gif)
 or  
![codecogseqn 3](https://cloud.githubusercontent.com/assets/2541209/13769121/4b0e83d0-ea3a-11e5-9cb9-1cbb06dedb3d.gif)
? I think it's the former (since the BCs are different, so the matrix is not symmetric). The below two lines are different:
1. https://github.com/rachelslaybaugh/NE155/blob/gh-pages/18-1d-fd-fvm/18-1d-fd-fvm.tex#L379
2. https://github.com/rachelslaybaugh/NE155/blob/gh-pages/18-1d-fd-fvm/18-1d-fd-fvm.tex#L410

**Comment by rachelslaybaugh** [comment]
Hi, ah--so the homogeneous case has an error. Yes, it should be the former. I'll correct the homog case.

**Comment by marwahaha** [comment]
Thanks!
