### ISSUE TITLE
day 23 notes (in day 18 folder)

### ISSUE THREAD

**Issue by marwahaha** [rachelslaybaugh/NE155#20]
1. What is e_{1}^{T}? Is it a way to estimate error?
   https://github.com/rachelslaybaugh/NE155/blob/gh-pages/18-1d-fd-fvm/23-1d-eig-fd-fvm.tex#L336
2. I think the below line has a typo -- since B is raised to the power of m, the dominance ratio should also be raised to the power of m:
   https://github.com/rachelslaybaugh/NE155/blob/gh-pages/18-1d-fd-fvm/23-1d-eig-fd-fvm.tex#L342

**Comment by marwahaha** [comment]
fixing number 2 via #21

**Comment by marwahaha** [comment]
And a question -- are we using e_1 to select the coefficient gamma_1? I'm not sure how to practically implement this, if we don't even know the value or vector of the eigenpair

**Comment by rachelslaybaugh** [comment]
For 1: $e_{1}^{T}$ is a vector with 1 in the first entry and zeros elsewhere; it selects the first row of $\ve{B}$ in the multiplication. 

correction will be posted. lmk if all that makes sense and we can close this issue.

**Comment by rachelslaybaugh** [comment]
oh, you don't need to worry about implementing the e_1^T; this is just for the error proof. does that help? (sorry, thought that last comment poste yesterday)

**Comment by rachelslaybaugh** [comment]
@marwahaha did the updates resolve this issue?

**Comment by marwahaha** [comment]
yes, thanks!
