### ISSUE TITLE
'lecture' misspelled in short description

### ISSUE THREAD

**Issue by kellyrowland** [rachelslaybaugh/NE155#9]
i've fixed it on my fork, but i don't think it gets included in PRs.

**Comment by rachelslaybaugh** [comment]
where? I don't know where you mean so I can't fix it.

**Comment by kellyrowland** [comment]
towards the top of the page, right under the 'Code' tab, it says 'ne155 lecutre materials'

**Comment by rachelslaybaugh** [comment]
thanks!
